ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Data/My/Model/MemberModel.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeRecordCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeRecordModel.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
- #12 
- 홈 아카이빙 컬렉션뷰 셀 애니메이션 처리
- 다음 풀리퀘에 남길게요
- 다음 풀리퀘에 남길게요
=> [Feat] #12 - [Feat] 홈뷰 UI 구현하기(중간)

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Data/My/Model/MemberModel.swift, ZOOC/ZOOC/Global/Extension/UICollectionReusableView+.swift, ZOOC/ZOOC/Global/Extension/UICollectionViewCell+.swift, ZOOC/ZOOC/Global/Extension/UIFont+.swift, ZOOC/ZOOC/Presentation/My/Cell/PetCollectionFooterView.swift, ZOOC/ZOOC/Presentation/My/Cell/PetCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/SettingMenuTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Controller/AppInformationViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyNoticeSettingViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift, ZOOC/ZOOC/Presentation/My/View/DeleteAccountAlertViewController.swift, ZOOC/ZOOC/Presentation/My/View/DeleteAccountView.swift, ZOOC/ZOOC/Presentation/My/View/FamilyCollectionView.swift, ZOOC/ZOOC/Presentation/My/View/MyNoticeSettingView.swift, ZOOC/ZOOC/Presentation/My/View/MyView.swift, ZOOC/ZOOC/Presentation/My/View/PetCollectionView.swift, ZOOC/ZOOC/Presentation/My/View/ProfileView.swift, ZOOC/ZOOC/Presentation/My/View/SettingMenuTableView.swift
- #18 
- 마이페이지 UI 변경
- 알림설정 UI 변경
-  마이페이지 회원탈퇴 UI 구성
- 나중에 수정할 게 있을수도?
closed #18
=> [Fix] #18 -  마이페이지 UI 수정

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Data/Home/APIModel/HomeArchiveResult.swift, ZOOC/ZOOC/Data/Home/APIModel/HomeMissionResult.swift, ZOOC/ZOOC/Data/Home/APIModel/HomePetResult.swift, ZOOC/ZOOC/Data/User.swift, ZOOC/ZOOC/Global/Constant/URLs.swift, ZOOC/ZOOC/Network/Base/BaseAPI.swift, ZOOC/ZOOC/Network/Home/HomeAPI.swift, ZOOC/ZOOC/Network/Home/HomeService.swift, ZOOC/ZOOC/Presentation/Base/BaseViewController.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveGridCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListWriterCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomePetCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift, ZOOC/ZOOC/Presentation/Home/View/HomeDetailArchiveCommentTextField.swift
- #29
- 홈뷰 서버통신
- 가이드뷰 분기 처리 안함
- 필터링 기능 안함
closed #29
=> [Feat] #29 - 홈뷰 서버 통신 

ZOOC/ZOOC/Application/SceneDelegate.swift, ZOOC/ZOOC/Data/Common/Model/User.swift, ZOOC/ZOOC/Network/Base/APIConstants.swift, ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift, ZOOC/ZOOC/Presentation/Base/ZoocAlertViewController.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeGuideCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyRegisterPetTableFooterView.swift, ZOOC/ZOOC/Presentation/My/Cell/MyAppInformationTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyFamilyCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyAppInformationView.swift, ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyNoticeSettingView.swift, ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift, ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
- #46 
- 기기대응을 위한 AutoLayout 수정
-
closed #46
=> [Fix] #46 - 기기대응을 위한 AutoLayout 수정

ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingChooseFamilyRoleView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingLoginView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
- #45
-  온보딩(초대코드 입력 전) 오토레이아웃 수정
- imageView contentMode
=> [Fix] #45 - 온보딩(초대코드 입력 전) 오토레이아웃 수정

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Application/SceneDelegate.swift, ZOOC/ZOOC/Data/Home/APIModel/HomeCommentRequest.swift, ZOOC/ZOOC/Network/Home/HomeAPI.swift, ZOOC/ZOOC/Network/Home/HomeService.swift, ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
- #49
- 댓글 작성기능 구현
- 최종은 조금 더 여유있게 끝내자
closed #49
=> [Fix] #49 - 과제 전 최종 점검

ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateCompletedView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
- #52 
- 온보딩 오토레이아웃 수정
- 기종 별로 이상하지 않은지 봐주세용
closed #52
=> [Feat] #52 - 온보딩 오토레이아웃 수정

ZOOC/ZOOC/Presentation/Base/ZoocAlertViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift
- #56 
- AlertViewController 배경색 및 라벨 색 수정
- Alert 뷰에 글씨 잘리고 줄 간격 안맞는 부분 수정
- 한번 테스트할 때 alert뷰 어떤지 봐주시면 조아용~
closed #56
=> [Fix] AlertViewController 배경색 및 라벨 색 수정 #56

ZOOC/ZOOC/Presentation/Home/Controller/HomeNoticeViewController.swift, ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyPetCollectionFooterView.swift, ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
- #57 
- 알람창 tableviewcell 선택 시 selectionStyle 변경
-  마이페이지 가족, 반려동물 CollectionView inset 추가
-  마이페지이 가족, 반려동물 구성원 수 라벨 AutoLayout 수정
- 시연 전 QA 반영 수정
closed #57
=> [Fix] #57 - UI관련 QA 반영하기 

ZOOC/ZOOC/Presentation/My/Cell/MyFamilyCollectionViewCell.swift
- #60 
- 마이페이지 가족 뷰 재사용 큐 문제 해결 
- 마이페이지 가족 뷰 재사용 큐 문제 해결 
closed #60
=> [Fix] #60 - 마이페이지 가족 뷰 재사용 큐 문제 해결 

ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyPetCollectionFooterView.swift, ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyRegisterPetTableFooterView.swift, ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyRegisterPetTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MySettingSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyNoticeSettingViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyEditProfileView.swift, ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift, ZOOC/ZOOC/Presentation/My/View/MyView.swift
- #73 
- 마이페이지 코드 리펙토링
- 마이페이지 코드 리펙토링
없습니다!
closed #73
=> [Refactor] #73 - 마이페이지 코드 리펙토링

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingAgreementTableHeaderView.swift, ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingRegisterPetTableFooterView.swift, ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift, ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingChooseFamilyRoleViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyCompletedViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingWelcomeViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingChooseFamilyRoleView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingLoginView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateCompletedView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
- #75 
- 온보딩뷰 리리팩토링
- 거의 안티티티티티 프라자프라자 수준으로 리리리리리 팩토링 팩토링 중인데영~
- 일단 혼자 뿌듯한 부분은 옵셔널 문법을 공부한다음 if let보다 guard let이 이쁜 곳에 알맞게 넣은(물론 나의 생각이지만) 부분!
소셜로그인이랑 textDidChange 부분 바꿨는데 이상하면 알려주시고 잘했으면 칭찬 이빠이 부탁합니당~
- 그리고 style(), hierarchy() 등으로 조금 더 세분화를 했는데 이것도 괜찮은지 피드백 부탁드리요!
없습니당!!!
closed #75
=> [Refactor] #75 - 온보딩뷰 리리팩토링

ZOOC/ZOOC/Data/My/Model/MyPetRegisterModel.swift, ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyPetCollectionFooterView.swift, ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyRegisterPetTableFooterView.swift, ZOOC/ZOOC/Presentation/My/Cell/MyAppInformationTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyDeleteAccountSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyFamilyCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyRegisterPetTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MySettingSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MySettingTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Controller/MyAppInformationViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyAppInformationView.swift, ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyEditProfileView.swift, ZOOC/ZOOC/Presentation/My/View/MyNoticeSettingView.swift, ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift, ZOOC/ZOOC/Presentation/My/View/MyView.swift
- #78 
- 온보딩 리리팩토링과 같은 방향으로 리팩토링 했습니다!
- 없습니다!
없습니다!
closed #78
=> [Refactor] #78 - 마이페이지뷰 리리팩토링 

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Data/Home/APIModel/HomeEmojiCommentRequest.swift, ZOOC/ZOOC/Data/Home/Model/EmojiModel.swift, ZOOC/ZOOC/Network/Home/HomeAPI.swift, ZOOC/ZOOC/Network/Home/HomeService.swift, ZOOC/ZOOC/Presentation/Home/Cell/EmojiCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift, ZOOC/ZOOC/Presentation/Home/View/EmojiBottomSheetViewController.swift, ZOOC/ZOOC/Presentation/Home/View/HomeDetailArchiveCommentView.swift, ZOOC/ZOOC/Presentation/Home/View/HomeDetailArchiveEmojiBottomSheet.swift
- #86
- 상세보기뷰 이모지 기능 구현했습니당.
- 현재 바텀시트는 백그라운드 탭시 내려갑니다.
- 저는 아래로 쓸어내리는 제스쳐시에도 바텀시트가 내려갔으면 합니다.
- 쭉아 오랜만이야,,
- iOS 흥미를 잃지않았구나 재밌네 요거
closed #86
=> [Feat] #86 - 상세보기뷰 이모지 기능 구현

ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
- #90
- 사진 하나 선택시 바로 ImagePicker 닫히게 구현했습니다
- 하 완료버튼 하나 올리기 왤케 어려운지 모르겠네여
- UI 변동사항 없음
closed #90
=> [Feat]  #90 - ImagePicker UX 개선

ZOOC/ZOOC/Application/AppDelegate.swift
- #112 
- Foreground 일때 알림 안오는 오류 해결 
- 생각보다 별거 없누
- 시뮬레이터에선 안됨
- 실제 디바이스에서만 됨
closed #112
=> [Fix] #112 Foreground 일때 알림 안오는 오류 해결 

ZOOC/ZOOC/Data/Common/APIModel/RecordResult.swift, ZOOC/ZOOC/Data/Home/APIModel/HomeDetailArchiveResult.swift
- #121 
- record, comment 정보에 본인이 작성한 기록/댓글인지를 추가한다. (isMyRecord & isMyComment)
- 없어여, just 빠른 반영
없어여
closed #121
=> [Chore] #121 - 기록하기 관련 API 수정 

ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
- #138
- 날짜 레벨 위치 제대로
- 새로고침시 뚝 끊기는 이슈, completion으로 닫히는 애니메이션 후 새로고침 하도록 구현
- 무
closed #138
=> [Chore] #138 - 홈뷰 애니메이션 개선

ZOOC/ZOOC/Application/AppDelegate.swift, ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyAppInformationHeaderView.swift, ZOOC/ZOOC/Presentation/My/Cell/MyAppInformationTableViewCell.swift, ZOOC/ZOOC/Presentation/My/View/MyNoticeSettingView.swift, ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift
- #142 
- 마이페이지뷰 기기대응
- 마이페이지 뷰 기기대응 했습니다
기존과 동일합니다!
closed #142
=> [Chore] #142 - 마이페이지뷰 기기대응

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, ZOOC/ZOOC/Application/AppDelegate.swift, ZOOC/ZOOC/Application/SceneDelegate.swift, ZOOC/ZOOC/Global/Error/AuthError.swift, ZOOC/ZOOC/Network/Foundation/ZoocInterceptor.swift
- #145 
- 모든 토큰 만료시 Sentry에 에러 보냄
- 모든 라이브러리 업데이트 한번 시원하게 했습니다~ 풀 받을 때 오래걸려도 이해해주삼요
- Sentry SPM 추가했습니다.
closed #145
=> [Add] #145 -   Sentry(Crashlytics)

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Data/UserDefaultsManager.swift, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveGuideViewController.swift, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeGuideViewController.swift, ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift, ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
- #141
- 버튼 수정
- 생략
생략
closed #141
=> [Chore] #141 -  온보딩뷰 기기대응 및 코드 수정 

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Data/UserDefaultsManager.swift, ZOOC/ZOOC/Global/Constant/EnternalURL.swift, ZOOC/ZOOC/Network/Archive/ArchiveAPI.swift, ZOOC/ZOOC/Network/Archive/ArchiveService.swift, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
- #148
- 게시물 삭제하기 기능 구현했습니다.
- isWriter Bool값을 통해 삭제하기 버튼을 띄울지 말지 분기처리함
- 게시물이 삭제되었을 시 dismiss하고 홈뷰를 갱신함.
closed #148
=> [Feat] #148 - 게시물 삭제하기 기능 구현

ZOOC/ZOOC/Application/AppDelegate.swift, ZOOC/ZOOC/Global/Constant/EnternalURL.swift, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift, ZOOC/ZOOC/Presentation/Base/BaseViewController.swift, ZOOC/ZOOC/Presentation/My/Cell/MyAppInformationTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/My/Controller/MyAppInformationViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyAppInformationView.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
- #149
- 커밋 참고
- 놉
놉
closed #149
=> [Chore] #149 - 마이페이지 수정

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift, ZOOC/ZOOC/Presentation/Base/BaseViewController.swift, ZOOC/ZOOC/Presentation/Base/ZoocImageController.swift
- #152
- 아카이빙 뷰에서 사진 선택시 전체 화면으로 전환되게 구현
- 해당 ImagVC 하단 슬라이드 제스처시 dismiss 되도록 구현
- 사진 전체화면을 사용하고 싶다면 `ZoocImageViewController`를 으로 present 하세요.
- 하단 제스처로 dismiss 하고 싶을 경우 BaseVC의 `addPanDismissGesture()` 를 dismiss 하고 싶은 VC의 viewDidLoad에서 호출하세요.
* 주의할점: dismiss하고픈 VC의 modalPresentationStyle은 `.overFullScreen`으로 설정해야한다.
그래야 자연스러움
https://github.com/TeamZOOC/ZOOC-iOS/assets/57269348/a16f0677-a8df-41f7-87f1-2707de5d8969
closed #152
=> [Feat] #152 - 사진 전체화면 및 다운로드 기능 구현

ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift
- #154
-히든 수정
- 히든 수정
closed #154
=> [Fix] Hidden 값 오류 해결 #154

ZOOC/ZOOC/Presentation/Record/Cell/RecordMissionCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterFourCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordCompleteViewController.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift, ZOOC/ZOOC/Presentation/Record/View/RecordMissionView.swift, ZOOC/ZOOC/Presentation/Record/View/RecordRegisterView.swift, ZOOC/ZOOC/Presentation/Record/View/RecordView.swift
- #144 
- 기록하기 미션하기뷰 기기대응
- multipleBy와 updateConstarint를 활용해서 오토 레이아웃 수정
- 근데 몇가지 좀 이상하게 보이는게 있는데, 가려지는 컴포넌트는 없음!
- 추후 다시 제대로 리팩토링 하겠습니다!
없습니다
closed #144
=> [Chore] #144 - 기록하기 미션하기뷰 기기대응

ZOOC/ZOOC/Data/Record/Model/RecordMissionViewModel.swift, ZOOC/ZOOC/Data/Record/Model/RecordModel.swift, ZOOC/ZOOC/Presentation/Home/View/HomeNoticeView.swift, ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift, ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
- #160 
- 미션하기 사진 선택시 갤러리창 dismiss 처리
- 반려동물 추가 버튼 클릭시 button 비활성화 처리
- 반려동물 사진 선택시 갤러리창 dismiss 처리
- 알림설정 스크롤 관련 문제 해결
- 미션하기 index 오류 해결하기
- 미션하기에 등록한 게시물 안나오는 이슈 해결
- 미션하기 기록하기 기기대응
- 미션하기에 등록한 게시물 안나오는 이슈는 서버랑 이야기하고 해결하겠습니다
없습니다
closed #160
=> [Fix] #160 - 기획 QA - 기록하기 미션하기 관련 이슈 해결

ZOOC/ZOOC/Data/Archive/APIModel/ArchiveResult.swift, ZOOC/ZOOC/Global/Constant/URLs.swift, ZOOC/ZOOC/Network/Archive/ArchiveAPI.swift, ZOOC/ZOOC/Network/Archive/ArchiveService.swift, ZOOC/ZOOC/Presentation/Archive/Cell/ArchiveCommentCollectionViewCell.swift, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift
- #164
- 댓글 삭제하기 기능 구현
- 신고하기 URL 받아야함
시로
closed #164
=> [Feat] #164 - 댓글 삭제하기 기능

ZOOC/ZOOC/Global/Extension/UIView+.swift, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift, ZOOC/ZOOC/Presentation/Archive/View/ArchiveCommentView.swift, ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingRegisterPetTableFooterView.swift, ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
- #170 
- 커밋 참고!
- 마이페이지 이미지 변경이 안된당 ㅜ
- 다음 이슈에서 Fix하자
closed #170
=> [FIX] #170 - 기획, 디자인 남은 QA 반영 

ZOOC/ZOOC.xcodeproj/project.pbxproj, ZOOC/ZOOC/Global/Constant/EnternalURL.swift, ZOOC/ZOOC/Global/Constant/TextLiteral.swift, ZOOC/ZOOC/Global/Extension/UIColor+.swift, ZOOC/ZOOC/Global/Utility/Device.swift, ZOOC/ZOOC/Network/My/MyService.swift, ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift, ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift, ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyAppInformationHeaderView.swift, ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift, ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift, ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift, ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift, ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
- #174
- 커밋 참고용
- 완료되지 않은 기획안들 메일 전송하기로 기능 구현하였음.
- 아직 XCode 업데이트 중이라 휴대폰 빌드가 되지 않아 일단 머지 후 수정사항있으면 수정하겠음!
closed #174
=> [CHORE] #174 - 장석우 Self QA
